apiVersion: zbn0922.github.com/v1
kind: Redis
metadata:
  labels:
    app.kubernetes.io/name: redis-operator
    app.kubernetes.io/managed-by: kustomize
  name: redis-sample
spec:
  replicas: 1
  image: redis:6
  storage: 1Gi
  autoScale: 
    maxReplicas: 5
    minReplicas: 3
    cpu: 5
  # TODO(user): Add fields here
