apiVersion: zbn0922.github.com/v1
kind: Redis
metadata:
  labels:
    app.kubernetes.io/name: redis-operator
    app.kubernetes.io/managed-by: kustomize
  name: redis-sample
spec:
  replicas: 2
  image: redis:7
  storage: 1Gi
  # TODO(user): Add fields here
